package entity;

// Generated May 11, 2012 3:56:49 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Executiontest generated by hbm2java
 */
public class Executiontest implements java.io.Serializable {

	private Integer id;
	private Date startdatatime;
	private Date finishdatatime;
	private int iduser;

	public Executiontest() {
	}

	public Executiontest(Date startdatatime, Date finishdatatime, int iduser) {
		this.startdatatime = startdatatime;
		this.finishdatatime = finishdatatime;
		this.iduser = iduser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getStartdatatime() {
		return this.startdatatime;
	}

	public void setStartdatatime(Date startdatatime) {
		this.startdatatime = startdatatime;
	}

	public Date getFinishdatatime() {
		return this.finishdatatime;
	}

	public void setFinishdatatime(Date finishdatatime) {
		this.finishdatatime = finishdatatime;
	}

	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

}
